### ISSUE TITLE
MovieInfo not functional.

### ISSUE THREAD

**Issue by JK98062** [SharkHunter/MovieInfo#10]
The MovieInfo plugin has not been functional at all since about the time UMS version 5 was released. (years ago)
SharkHunter, could this please be updated to run on Current Builds of UMS; v7.0.0 at time of writing; or possibly pass on the source code to someone who can modify/adapt it to operational working order?

**Comment by SharkHunter** [comment]
The whole idea with github and public code is that anyone can make thier own fork and maintain it if they feel loke it. Now the current developers don't feel the need to maintain ANY plugins. There were code changes that broke the plugins and the solution for those people was that I fixed thier mess which I didn't want to d. Feel free to foork or whatever you want.
